/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2013-06-13 15:19:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class accueil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\"> \r\n");
      out.write("\t<title>Accueil</title> \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>  \r\n");
      out.write("\t<link rel=\"SHORTCUT ICON\" href=\"img/logo/logof3.jpg\">\r\n");
      out.write("\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\t<link href=\"css/formationscss.css\" rel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("</head> \r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Entete --> \r\n");
      out.write("<div class=\"navbar navbar-fixed-top\" >\r\n");
      out.write("  <div class=\"navbar-inner\">\r\n");
      out.write("\t  <div class=\"container\"> \r\n");
      out.write("\t\t<a class=\"brand\" href=\"./accueil\" style=\"padding-top: 8px; padding-bottom: 0px;\">\r\n");
      out.write("\t      <b style=\"color:#0088cc;font-weight:bold;font-family:'Bauhaus 93';font-size:25px;margin-right:-5px;\">F</b>\r\n");
      out.write("\t      <span style=\"color:#555;font-size:18px;\">ormations</span>\r\n");
      out.write("\t    </a> \r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<!-- Barre de menu --> \r\n");
      out.write("\t    <ul class=\"nav\"> \r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t<li class=\"divider-vertical\"></li>   \r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"./accueil\"><i class=\"icon-home\"></i>  Accueil</a></li> \r\n");
      out.write("\t\t\t<li class=\"divider-vertical\"></li>  \r\n");
      out.write("\t\t\t<li><a href=\"./formations\">  Formations</a></li> \r\n");
      out.write("\t\t\t<li class=\"divider-vertical\"></li>  \r\n");
      out.write("\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">  Candidatures\r\n");
      out.write("\t\t\t      <b class=\"caret\"></b>\r\n");
      out.write("\t\t\t    </a>\r\n");
      out.write("\t\t\t    <ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t       <li><a href=\"./clientsformation\"> Clients et formations</a></li>\r\n");
      out.write("\t\t\t       <li><a href=\"./formationsclient\"> Clients par formation</a></li>\r\n");
      out.write("\t\t\t    </ul>\r\n");
      out.write("\t\t\t</li> \r\n");
      out.write("\t\t\t<li class=\"divider-vertical\"></li> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    </ul> \r\n");
      out.write("\t    \r\n");
      out.write("\t    <form id=\"searchForm\" action=\"./formations?op=filter\" method=\"GET\" class=\"navbar-search pull-right\">  \r\n");
      out.write("\t\t  <input type=\"text\" class=\"input-medium search-query\" placeholder=\"Rechercher\" id=\"cours\" name=\"cours\">  \r\n");
      out.write("\t\t</form> \r\n");
      out.write("\t\t\r\n");
      out.write("\t </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Corps -->\r\n");
      out.write("<div id=\"banniere\" style=\"height:60%\">\r\n");
      out.write("\t<img src=\"./img/banniere16.jpg\" width=\"100%\" height=\"8%\" /> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container conteneurwtborder\" id=\"fadeOutIn\"> \r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<a href=\"./formations\">\r\n");
      out.write("\t        <div class=\"span2 hero-unit divbtn\">\r\n");
      out.write("\t          <p>Formations<br/>et inscriptions</p>  \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <a href=\"./formationsclient\">\r\n");
      out.write("\t        <div class=\"span2 hero-unit divbtn\">\r\n");
      out.write("\t           <p>Liste des Clients<br/>par formation</p> \r\n");
      out.write("\t       </div>\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <a href=\"./clientsformation\">\r\n");
      out.write("\t        <div class=\"span2 hero-unit divbtn\">\r\n");
      out.write("\t           <p>Liste des Clients<br/>et formations</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write(" \r\n");
      out.write("<!-- Pied de page -->  \r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("      <div class=\"container\" id=\"footer\">   \r\n");
      out.write("    \t  &copy; Copyright 2013 | LO54 - Lodjeu - Libam -Ntieche\r\n");
      out.write("      </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("\t\t$('#fadeOutIn').fadeOut(0);\r\n");
      out.write("\t\t$('#fadeOutIn').fadeIn(500);\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
